env = "development"

host = "127.0.0.1"
port = "3050"

[db]
username = "darshit"
password = "Pass@123"
host = "127.0.0.1"
database = "main_db"

# migration, seeder config
dialect = "mysql"
seederStorage = "sequelize"

# models default config
operatorsAliases = false

  [db.define]
  freezeTableName = true
  engine = "InnoDB"
  charset = "utf8mb4"
  collate = "utf8mb4_general_ci"

[session]
secret = 'update-for-prod-in_local-production.toml'
resave = true
saveUninitialized = true

  [session.cookie]
  maxAge = 6048e5 # 7 days
